
f_name=input("enter your father's name: ")
print(f_name)
f_age=int(input("enter your father's age: "))
print(f_age)
f_weight=float(input("enter your father's weight: "))
print(f_weight)
print(f_name,f_age,f_weight,sep="*")

m_name=input("enter your mother's name: ")
print(m_name)
m_age=int(input("enter your mother's age: "))
print(m_age)
m_weight=float(input("enter your mother's weight: "))
print(m_weight)
print(m_name,m_age,m_weight,sep="/")

s_name=input("enter your sister's name: ")
print(s_name)
s_age=int(input("enter your sister's age: "))
print(s_age)
s_weight=float(input("enter your sister's weight: "))
print(s_weight)
print(s_name,s_age,s_weight,sep="#")

my_name=input("enter your name: ")
print(my_name)
my_age=int(input("enter your  age: "))
print(my_age)
my_weight=float(input("enter your weight: "))
print(my_weight)
print(my_name,my_age,my_weight,sep="$")